wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.18
    start_time: 1726308866
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      4: 3.8.18
      5: 0.12.18
      8:
      - 5
batch_size:
  desc: null
  value: 108
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.001
